### ISSUE TITLE
ci/cd for issuer agent

### ISSUE THREAD

**Issue by Rithwik0480** [dhiway/issuer-agent#17]
**TODO**

- [ ]  git hub workflow for issuer-agent
- [ ]  on PR checks installation of npm dependencies
- [ ]  checks build docker image
